CREATE DATABASE chimhaha;

USE chimhaha;


CREATE TABLE board(
	id INT PRIMARY KEY AUTO_INCREMENT
	,title VARCHAR(50) NOT NULL
	,content VARCHAR(1000) NOT NULL
	,write_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,delete_flg CHAR(1) NOT NULL DEFAULT '0'
	,delete_date DATETIME DEFAULT NULL
);

COMMIT;