CREATE DATABASE bcd;

USE bcd;


CREATE TABLE lists(
	id INT PRIMARY KEY AUTO_INCREMENT
	,content VARCHAR(50) NOT NULL
	,write_date DATE NOT NULL DEFAULT CURDATE()
	,del_date DATETIME DEFAULT NULL
	,chk_date DATETIME DEFAULT NULL
	,to_date DATE NOT NULL
	,up_date DATE DEFAULT NULL
	,ten_flg CHAR(1) NOT NULLbcd
);

COMMIT;